######################################################################################
# This program creates a function to generate and print the comparison results of   ##
# observed and predicted defibrillation performance of design-A devices for the     ##
# clinical study.                                                                   ##
# Inputs: MCMC samples generated by the Bayesian analysis for the following model   ##
# parameters:                                                                       ##
# Number of patients in the design-A and design-B studies combined -N               ##
# Number of patients in the Design-B feasibility study - N1                         ##
# Number of MCMC samples - ngibbs                                                   ##
# MCMC sample for the slope parameter - G                                           ##
# MCMC samples for the E50 parameter - Theta                                        ##
# MCMC samples for the scale and shrinkage parameters - Delta, Kappa                ##
######################################################################################

# Define a function to print design-A device Defib Efficacy estimation Results for a 
# new clinical study of a specified size

PrintDesAReslts <- function(ngibbs,N,Nv,N1,G,Theta) {
  
  # Initialize the matrix Theta1 to store E50 values for design-A devices
  Npts <- N-N1 # All design-A clinical study patients
  Npts_PC <- Npts-(N_sfs+N_s+N_ff+N_fs) # Design-A patients who completed the test 
                                        # protocol

  Theta1 <- array(0,dim=c(ngibbs,Npts))
  #Get the E50 values for design-A devices from the posterior samples
  Theta1 <- Theta[,-c(Npts+1:N)]
  dim(Theta1); q=G %*% t(rep(1,Npts)); dim(q);
  
  ## Initialize the matrices to store estimated defib efficacy probabilities using
  ## MCMC samples
  p60 <- matrix(0,nrow=ngibbs,ncol=Npts)
  p65 <- matrix(0,nrow=ngibbs,ncol=Npts)
  p70 <- matrix(0,nrow=ngibbs,ncol=Npts)
  # Initialize the matrices to hold binomial counts data
  ImpS_60J <- matrix(0,nrow=ngibbs,ncol=Npts)
  S70 <- matrix(0,nrow=ngibbs,ncol=Npts)
  # Initialize vectors to store various defibrillation efficacy probabilities.  
  # This stored data is used to compute 95% credible intervals for the estimated 
  # defib efficacies.
  ProbS_60J <- numeric(ngibbs)  
  ProbS_65J <- numeric(ngibbs)    
  ProbS_70J <- numeric(ngibbs)   
  ProbSS_60J <- numeric(ngibbs) 
  ProbSS_65J <- numeric(ngibbs)   
  ProbSS_70J <- numeric(ngibbs) 

  ProbImpS_60J <- numeric(ngibbs)
  ProbImpf_60J <- numeric(ngibbs)
  PrS70givenImpS60 <- numeric(ngibbs)  
  
  for(i in 1:ngibbs){
    # OBTAIN PROBABILITY OF SUCCESSFUL SHOCK
    
    p70[i,] <- 1/(1+(Theta1[i,]/70)^G[i])
    p65[i,] <- 1/(1+(Theta1[i,]/65)^G[i])
    p60[i,] <- 1/(1+(Theta1[i,]/60)^G[i]) 
    # For each MCMC sample, store the average defib efficacy at each different energy
    # level
     
    ProbS_60J[i] <- mean(p60[i,]) # Avg. Prob. of 1st shock success at 60J
    ProbS_65J[i] <- mean(p65[i,]) # Avg. Prob. of 1st shock success at 65J
    ProbS_70J[i] <- mean(p70[i,]) # Avg. Prob. of 1st shock success at 70J 

    ProbSS_60J[i] <- mean((p60[i,])^2) # Avg. Prob. of 1st & 2nd shock success at 60J
    ProbSS_65J[i] <- mean((p65[i,])^2) # Avg. Prob. of 1st & 2nd shock success at 65J   
    ProbSS_70J[i] <- mean((p70[i,])^2) # Avg. Prob. of 1st & 2nd shock success at 70J   
    # Compute the average probability of implant sucess (2S in a row out of 4 shocks)
    # at 60J for each MCMC sample
    ProbImpS_60J[i] <- mean(ProbSS_60J[i] #SS
                            + p60[i,]*(1-p60[i,])*(p60[i,])^2  #SFSS
                            + (1-p60[i,])*(p60[i,])^2  #FSS
                            + (1-p60[i,])^2*(p60[i,])^2) #FFSS
    ProbImpf_60J[i] <- 1-ProbImpS_60J[i]
    
    # It is not possible to directly compute the conditional probability of success at
    # 70J given implant success at 60J because the success probabilities within 
    # patients have unknown correlations. So, we use the following Binomial counts
    # data to compute the conditional probability
    
    #Generate success/fail counts for 1 - 4 shocked episodes at different energies
    
    Shk1_60 <- rbinom(n=Npts,size=1,prob=p60[i,])
    Shk2_60 <- rbinom(n=Npts,size=1,prob=p60[i,])
    Shk3_60 <- rbinom(n=Npts,size=1,prob=p60[i,])
    Shk4_60 <- rbinom(n=Npts,size=1,prob=p60[i,])
    Shk1_70 <- rbinom(n=Npts,size=1,prob=p70[i,])

    # Get counts of design-A device implant sucess (2S in a row out of 4 shocks) 
    # as follows
    ImpS_60J[i,] <- ifelse((((Shk1_60==1) & (Shk2_60 == 1)) | ((Shk1_60==0) 
                  & (Shk2_60 == 1) & (Shk3_60 == 1)) | ((Shk1_60==1) & (Shk2_60==0)
                  & (Shk3_60 == 1) & (Shk4_60 == 1)) | ((Shk1_60==0) & (Shk2_60==0) 
                  & (Shk3_60 == 1) & (Shk4_60 == 1))), 1,0) 
    S70[i,] = ifelse(Shk1_70==1,1,0)
    # Compute observed implant success in design-A device clinical study
    ObsImpS_60J <- (Nv$N_ss+Nv$N_sfss+Nv$N_fss+Nv$N_ffss)/Npts
   
    # Determine conditional probability of success at 70J given that implant success 
    # at 60J
    PrS70givenImpS60[i] <- mean(S70[i,][ImpS_60J[i,]==1],na.rm=TRUE)
    }
  
  ## Determine average probability of 1st shock success at various energy levels
  PrS_70 <- mean(p70)
  PrS_65 <- mean(p65)
  PrS_60 <- mean(p60)
  ObsPrs_60 <- (Nv$N_ss+Nv$N_sfss+Nv$N_sff+Nv$N_sfs+Nv$N_s)/Npts
  ## Determine average probability that both 1st and 2nd shocks are successful at 
  ## various energy levels
  PrSS_60 <- mean(p60^2); # S+S at 60J
  PrSS_65 <- mean(p65^2); # S+S at 65J
  PrSS_70 <- mean(p70^2); # S+S at 70J
  # Determine the observed probability that both 1st and 2nd shcoks are successful
  ObsPrSS_60 <- Nv$N_ss/(Npts-Nv$N_s) #Removed the pts who had only one shock

  # Probability calculations for additional outcomes (besides PrSS_60) with implant 
  # success at 60J
  PrSfSS_60 <- mean(p60*(1-p60)*p60*p60) #S+F+S+S at 60J
  PrfSS_60 <- mean((1-p60)*p60^2) #F+S+S at 60J
  PrffSS_60 <- mean((1-p60)^2*p60^2) #F+F+S+S at 60J

  # Compute the probability of design-A device clinical study implant success for 
  # 60J (10J safety margin with 70J max output device) shocks
  prImpSuc_60 <- PrSS_60 + PrSfSS_60 + PrfSS_60 + PrffSS_60 
  # Compute observed probability of implant success based on all patients
  ObsprImpSuc_60 <- (Nv$N_ss+Nv$N_sfss+Nv$N_fss+Nv$N_ffss)/Npts
  # Compute observed probability of implant success based only on those patients
  # who completed implant testing protocol
  ObsprImpSuc_60PC <- (Nv$N_ss+Nv$N_sfss+Nv$N_fss+Nv$N_ffss)/Npts_PC
  
  # Compute probabilities of design-A device clinical study implant failure for
  # 60J shocks
  prImpfail_60 <- 1-prImpSuc_60
  ## Determine average conditional probability of Success at 70J given 
  ## implant success at 60J 
 
  PrAvgS70givenImpS60 <- mean(PrS70givenImpS60,na.rm=TRUE)

  # Determine 95% Credible Intervals for various types of defibrillation efficacy
  # estimates
  PrS95CI_60J <- quantile(ProbS_60J, probs=c(0.025,0.975),na.rm=FALSE, names=FALSE, 
                          type=7)
  PrS95CI_65J <- quantile(ProbS_65J, probs=c(0.025,0.975),na.rm=FALSE, names=FALSE, 
                          type=7)
  PrS95CI_70J <- quantile(ProbS_70J, probs=c(0.025,0.975),na.rm=FALSE, names=FALSE, 
                          type=7)  
  
  PrSS95CI_60J <- quantile(ProbSS_60J, probs=c(0.025,0.975),na.rm=FALSE, names=FALSE, 
                           type=7)  
  PrSS95CI_65J <- quantile(ProbSS_65J, probs=c(0.025,0.975),na.rm=FALSE, names=FALSE, 
                           type=7)    
  PrSS95CI_70J <- quantile(ProbSS_70J, probs=c(0.025,0.975),na.rm=FALSE, names=FALSE, 
                           type=7)    
  
  PrImpS95CI_60J <- quantile(ProbImpS_60J, probs=c(0.025,0.975),na.rm=FALSE,
                             names=FALSE, type=7) 
  
  PrImpf95CI_60J <- quantile(ProbImpf_60J, probs=c(0.025,0.975),na.rm=FALSE, 
                             names=FALSE, type=7) 
  Pr95CI_S70givenImpS60 <- quantile(PrS70givenImpS60, probs=c(0.025,0.975),na.rm=FALSE,
                            names=FALSE, type=7) 
  
  
  cat(paste("PREDICTIONS for design-A device clinical study with",Npts," pts. based",
      "\non scalable model fitted to 325 design-A and",N1,"design-B patients' data\n"))
  print(c(
    sprintf("Predicted Probability 1st shock success at 60J: %.1f (95CI: %.1f - %.1f) –
    (model) Vs. %.1f (design-A study)", 100*PrS_60, 100*PrS95CI_60J[1],
    100*PrS95CI_60J[2],100*ObsPrs_60),
    sprintf("Predicted Probability of 1st shock success at 65J: %.1f (95CI: %.1f –
    %.1f)", 100*PrS_65, 100*PrS95CI_65J[1], 100*PrS95CI_65J[2]),
    sprintf("Predicted Probability of 1st shock success at 70J: %.1f (95CI: %.1f –
    %.1f)", 100*PrS_70, 100*PrS95CI_70J[1], 100*PrS95CI_70J[2]),
    sprintf("Predicted Probability of S + S (Success in 1st and 2nd shocks) at 60J: %.1f
    (95CI: %.1f - %.1f) - (model) Vs. %.1f (design-A study)", 100*PrSS_60,
    100*PrSS95CI_60J[1], 100*PrSS95CI_60J[2],100*ObsPrSS_60),
    sprintf("Predicted Probability of S + S (Success in 1st and 2nd shocks) at 65J: %.1f
    (95CI: %.1f - %.1f)",100*PrSS_65, 100*PrSS95CI_65J[1], 100*PrSS95CI_65J[2]),   
    sprintf("Predicted Probability of S + S (Success in 1st and 2nd shocks) at 70J: %.1f
    (95CI: %.1f - %.1f)",100*PrSS_70, 100*PrSS95CI_70J[1], 100*PrSS95CI_70J[2]),          
    sprintf("Predicted Probability of 2 of 4 implant success with 60J shocks: %.1f
    (95CI: %.1f - %.1f)- (model) Vs. %.1f (design-A study)", 100*prImpSuc_60,
    100*PrImpS95CI_60J[1], 100*PrImpS95CI_60J[2],100*ObsprImpSuc_60PC),
    sprintf("Predicted Probability of failure to pass 2 of 4 implant criterion with 60J
    Shocks: %.1f (95CI: %.1f - %.1f)", 100*prImpfail_60, 100*PrImpf95CI_60J[1],
    100*PrImpf95CI_60J[2]),
    sprintf("Predicted Probability of success at 70J given that 2 of 4 implant success
    with 60J shocks: %.1f (95CI: %.1f - %.1f)", 100*PrAvgS70givenImpS60,
    100*Pr95CI_S70givenImpS60[1], 100*Pr95CI_S70givenImpS60[2])
    ))       
}
